jwt:
  expire-time: 3600
  header: X-API-TOKEN
  signing-key: BDJvVGFvgDGvHGFVF
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    # Use a strong password in real world
    password: letspartyreturn
    url: jdbc:mysql://localhost:3306/letspartyreturn
    username: letspartyreturn
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
server:
contextPath: /letsparty